Refactored by duplicating expected binary architectures and verification script accross all three GitHub workflows as per Louis preference

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -24,19 +24,24 @@ jobs:
         include:
           - os: ubuntu-latest
             target: x86_64-unknown-linux-musl
+            binary: x86-64
             use-cross: true
           - os: ubuntu-latest
             target: aarch64-unknown-linux-musl
+            binary: aarch64
             use-cross: true
           # macos>=14 runs exclusively on aarch64 and will thus fail to execute properly for x64
           - os: macos-13
             target: x86_64-apple-darwin
+            binary: x86_64
             use-cross: false
           - os: macos-latest
             target: aarch64-apple-darwin
+            binary: arm64
             use-cross: false
           - os: windows-latest
             target: x86_64-pc-windows-msvc
+            binary: x86-64
             use-cross: false
     steps:
       - name: Checkout repository
@@ -67,7 +72,14 @@ jobs:
           if [[ "${{ matrix.target }}" == *"windows"* ]]; then
             BINARY_PATH="${BINARY_PATH}.exe"
           fi
-          ./bin/verify-binary-architecture.sh "${{ matrix.target }}" "$BINARY_PATH"
+
+          if ! file -b "$BINARY_PATH" | grep -q "${{ matrix.binary }}"; then
+            echo "error: Architecture mismatch"
+            echo "Expected architecture: '${{ matrix.binary }}'"
+            echo "Found binary type: '$(file -b "$BINARY_PATH")'"
+            exit 1
+          fi
+          echo "ok: Architecture match"
 
       - name: Build archive
         shell: bash
